---
- name: Setup Sway Desktop Environment with wpgtk
  hosts: localhost
  become: false
  vars:
    config_dir: "{{ user_home }}/.config"
    
  roles:
    - role: system_dependencies
      tags: ['dependencies', 'system']
      when: not skip_system_dependencies | bool
    
    - role: wpgtk
      tags: ['wpgtk', 'theming']
    
    - role: sway
      tags: ['sway', 'wm']
    
    - role: waybar
      tags: ['waybar', 'bar']
    
    - role: ulauncher
      tags: ['ulauncher', 'launcher']
    
    - role: kitty
      tags: ['kitty', 'terminal']
